os:
  - osx
osx_image: xcode11.2

env:
  global:
    - PATH=/usr/local/opt/qt/bin:$PATH
    - LDFLAGS=-L/usr/local/opt/qt/lib
    - CPPFLAGS=-I/usr/local/opt/qt/include
    - PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig
    
    
addons:
  homebrew:
    packages:
      - make
      - ninja

script:
  - make clean
  - make tools
  - make
  - tar -cf - PathOfBuilding.app | xz -c > PathOfBuilding.darwin.tar.xz


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "${TRAVIS_BUILD_DIR}/PathOfBuilding.darwin.tar.xz"
  skip_cleanup: true
